version: "3.9"
services:
  db:
    image: postgres:16
    container_name: pr-postgres
    environment:
      POSTGRES_DB: pr_service
      POSTGRES_USER: pr_user
      POSTGRES_PASSWORD: pr_pass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pr_user -d pr_service"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build: .
    container_name: pr-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
